const DUMMY_EXPENSES = [
  {
    month: "Abril",
    year: "2024",
    owner: "Mauri",
    name: "Farmacia DULAC",
    category: "Farmacia",
    description: "Pañales",
    creditCard: "VISA BLACK",
    quota: "1/3",
    price: 30000,
    edit: false,
  },
  {
    month: "Mayo",
    year: "2024",
    owner: "Pau",
    name: "Claro",
    category: "Factura",
    description: "Abono",
    creditCard: "MASTERCARD BLACK",
    quota: "2/3",
    price: 19000,
    edit: false,
  },
  {
    month: "Mayo",
    year: "2025",
    owner: "Mauri",
    name: "Supermercado Avellaneda",
    category: "Supermercado",
    description: "Provista",
    creditCard: "MASTERCARD BLACK",
    quota: "1/1",
    price: 75000,
    edit: false,
  },
  {
    month: "Mayo",
    year: "2024",
    owner: "Ana",
    name: "La Ventana",
    category: "Restaurante",
    description: "Cena",
    creditCard: "VISA GOLD",
    quota: "1/1",
    price: 45000,
    edit: false,
  },
  {
    month: "Mayo",
    year: "2025",
    owner: "Lucas",
    name: "Apple Store",
    category: "Electrónica",
    description: "iPhone 12",
    creditCard: "AMEX PLATINUM",
    quota: "1/12",
    price: 120000,
    edit: false,
  },
  {
    month: "Marzo",
    year: "2024",
    owner: "Carla",
    name: "Cine Hoyts",
    category: "Entretenimiento",
    description: "Entradas cine",
    creditCard: "VISA BLACK",
    quota: "1/1",
    price: 15000,
    edit: false,
  },
  {
    month: "Febrero",
    year: "2025",
    owner: "Sofía",
    name: "Zara",
    category: "Ropa",
    description: "Chaqueta",
    creditCard: "MASTERCARD SILVER",
    quota: "1/4",
    price: 80000,
    edit: false,
  },
  {
    month: "Enero",
    year: "2024",
    owner: "Leo",
    name: "Gym Club",
    category: "Deportes",
    description: "Membresía anual",
    creditCard: "VISA BLACK",
    quota: "1/1",
    price: 45000,
    edit: false,
  },
  {
    month: "Febrero",
    year: "2024",
    owner: "Maria",
    name: "Starbucks",
    category: "Cafetería",
    description: "Café y pastel",
    creditCard: "VISA GOLD",
    quota: "1/1",
    price: 7000,
    edit: false,
  },
  {
    month: "Marzo",
    year: "2025",
    owner: "Juan",
    name: "Movistar",
    category: "Factura",
    description: "Internet hogar",
    creditCard: "MASTERCARD BLACK",
    quota: "1/1",
    price: 20000,
    edit: false,
  },
  {
    month: "Abril",
    year: "2025",
    owner: "Elena",
    name: "Ferretería San Juan",
    category: "Hogar",
    description: "Herramientas",
    creditCard: "AMEX GOLD",
    quota: "1/6",
    price: 90000,
    edit: false,
  },
  {
    month: "Mayo",
    year: "2025",
    owner: "Roberto",
    name: "Toyota",
    category: "Automóvil",
    description: "Servicio anual",
    creditCard: "VISA BLACK",
    quota: "1/1",
    price: 60000,
    edit: false,
  },
  {
    month: "Junio",
    year: "2024",
    owner: "Mauri",
    name: "Netflix",
    category: "Entretenimiento",
    description: "Suscripción mensual",
    creditCard: "VISA BLACK",
    quota: "1/1",
    price: 1200,
    edit: false,
  },
  {
    month: "Julio",
    year: "2024",
    owner: "Pau",
    name: "Amazon",
    category: "Compras en línea",
    description: "Libro de cocina",
    creditCard: "MASTERCARD BLACK",
    quota: "1/1",
    price: 3500,
    edit: false,
  },
  {
    month: "Agosto",
    year: "2024",
    owner: "Ana",
    name: "Uber",
    category: "Transporte",
    description: "Viaje al aeropuerto",
    creditCard: "VISA GOLD",
    quota: "1/1",
    price: 2500,
    edit: false,
  },
  {
    month: "Septiembre",
    year: "2024",
    owner: "Mauri",
    name: "Spotify",
    category: "Entretenimiento",
    description: "Suscripción mensual",
    creditCard: "AMEX PLATINUM",
    quota: "1/1",
    price: 500,
    edit: false,
  },
];

export default DUMMY_EXPENSES;
